apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: cauahrq/catalog-service:v1
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: '3001'
            - name: DATABASE_HOST
              value: 'host.docker.internal'
            - name: DATABASE_PORT
              value: '5432'
            - name: DATABASE_USERNAME
              value: 'postgres'
            - name: DATABASE_PASSWORD
              value: '123456'
            - name: DATABASE_NAME
              value: 'catalog'
      restartPolicy: Always
