apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: CATALOG_IMAGE
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '128Mi'
              cpu: '250m'
          env:
            - name: PORT
              value: '3001'
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: databaseHost
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: databasePort
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: databaseUsername
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: databasePassword
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: databaseName
      restartPolicy: Always
