apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-catalog-service
  labels:
    app: catalog-service
spec:
  secretStoreRef:
    name: mysecretstore
    kind: SecretStore
  target:
    name: aws-secret
  data:
    - secretKey: databaseHost
      remoteRef:
        key: 'nodejs-microservices-catalog'
        property: DATABASE_HOST
    - secretKey: databasePort
      remoteRef:
        key: 'nodejs-microservices-catalog'
        property: DATABASE_PORT
    - secretKey: databaseUsername
      remoteRef:
        key: 'nodejs-microservices-catalog'
        property: DATABASE_USERNAME
    - secretKey: databasePassword
      remoteRef:
        key: 'nodejs-microservices-catalog'
        property: DATABASE_PASSWORD
    - secretKey: databaseName
      remoteRef:
        key: 'nodejs-microservices-catalog'
        property: DATABASE_NAME
