//category
export const CREATE_CATEGORY_FACTORY = 'CREATE_CATEGORY_FACTORY';
export const FIND_CATEGORIES_FACTORY = 'FIND_CATEGORIES_FACTORY';

//media
export const CREATE_MEDIA_FACTORY = 'CREATE_MEDIA_FACTORY';
export const FIND_MEDIAS_FACTORY = 'FIND_MEDIAS_FACTORY';
export const UPDATE_MEDIA_FACTORY = 'UPDATE_MEDIA_FACTORY';
